/**
 * External Renderer Example: PDF-Ready Brochure
 *
 * This demonstrates how to write a third-party renderer for intent-compiler.
 * Drop this file into any directory and run:
 *   intentc renderer add ./examples/renderers
 *
 * A renderer is just: { meta: RendererMeta, render: (ir: IntentIR) => string }
 */

import type { IntentIR, RendererMeta } from '../../src/renderers/registry';

export const meta: RendererMeta = {
  id: 'pdf-brochure',
  name: 'PDF-Ready Brochure',
  description: 'A4-optimized brochure layout. Print to PDF (Ctrl+P) for a polished document.',
  domain: 'web_page', // Can also work with document domain IRs
  outputFormat: 'html',
  version: '1.0.0',
  author: 'Intent Compiler Community',
  priority: 85,
};

export function render(ir: IntentIR): string {
  const sorted = [...ir.layout].sort((a, b) => a.priority - b.priority);
  const meta = ir.intent;

  const content = sorted
    .map((s) => {
      const c = s.content as Record<string, unknown>;
      switch (s.type) {
        case 'hero':
          return `
<div class="cover" style="page-break-after:always;text-align:center;padding:120px 40px">
  <h1 style="font-size:2.5rem;color:#1a1a1a;margin-bottom:12px">${c.headline || ''}</h1>
  ${c.subheadline ? `<p style="font-size:1.2rem;color:#666">${c.subheadline}</p>` : ''}
</div>`;
        case 'features': {
          const items = (c.items as Array<{ title: string; description: string }>) || [];
          return `
<div style="page-break-before:always;padding:40px">
  <h2 style="color:#2563eb;border-bottom:2px solid #2563eb;padding-bottom:8px;margin-bottom:24px">${c.title || 'Features'}</h2>
  ${items.map((item) => `
  <div style="margin-bottom:24px;padding:16px;background:#f8fafc;border-radius:4px">
    <h3 style="color:#1a1a1a;margin-bottom:4px">${item.title}</h3>
    <p style="color:#666;line-height:1.6">${item.description}</p>
  </div>`).join('')}
</div>`;
        }
        case 'specs': {
          const items = (c.items as Array<{ label: string; value: string }>) || [];
          return `
<div style="page-break-before:always;padding:40px">
  <h2 style="color:#2563eb;border-bottom:2px solid #2563eb;padding-bottom:8px;margin-bottom:24px">${c.title || 'Specifications'}</h2>
  <table style="width:100%;border-collapse:collapse">
    ${items.map((item) => `
    <tr style="border-bottom:1px solid #e5e7eb">
      <td style="padding:12px 16px;font-weight:600;color:#1a1a1a;width:40%">${item.label}</td>
      <td style="padding:12px 16px;color:#666">${item.value}</td>
    </tr>`).join('')}
  </table>
</div>`;
        }
        case 'faq': {
          const items = (c.items as Array<{ question: string; answer: string }>) || [];
          return `
<div style="page-break-before:always;padding:40px">
  <h2 style="color:#2563eb;border-bottom:2px solid #2563eb;padding-bottom:8px;margin-bottom:24px">${c.title || 'FAQ'}</h2>
  ${items.map((item) => `
  <div style="margin-bottom:16px">
    <p style="font-weight:600;color:#1a1a1a;margin-bottom:4px">Q: ${item.question}</p>
    <p style="color:#666;line-height:1.6">A: ${item.answer}</p>
  </div>`).join('')}
</div>`;
        }
        default:
          return '';
      }
    })
    .join('\n');

  return `<!DOCTYPE html>
<html lang="${meta.language?.split('-')[0] || 'en'}">
<head>
<meta charset="UTF-8">
<title>${meta.summary} — Brochure</title>
<style>
@page { size: A4; margin: 20mm; }
body { font-family: 'Georgia', serif; color: #1a1a1a; line-height: 1.7; max-width: 210mm; margin: 0 auto; padding: 0; }
h1, h2, h3 { font-family: 'Inter', 'PingFang SC', sans-serif; }
@media print { body { -webkit-print-color-adjust: exact; } }
</style>
</head>
<body>
${content}
<p style="text-align:center;color:#999;font-size:0.8rem;margin-top:40px;page-break-before:always">
  Generated by intent-compiler · pdf-brochure renderer
</p>
</body>
</html>`;
}
